from app import db, app
from app.models import User, Post,Category,Brand,Product,Area,Distric,MTR,Condition,Meetup,Image


app_context = app.app_context()
app_context.push()
db.drop_all()
db.create_all()

u1 = User(username='john', email='john@example.com')
u2 = User(username='susan', email='susan@example.com')
u1.set_password("P@ssw0rd")
u2.set_password("P@ssw0rd")
db.session.add(u1)
db.session.add(u2)
u1.follow(u2)
u2.follow(u1)

p1 = Post(body='my first post!', author=u1)
p2 = Post(body='my first post!', author=u2)
brand = Brand(name='apple')
brand1 = Brand(name='Samsung')
category1 = Category(name='Computers & Tech')
category2 = Category(name='Mobile Phones & Gadgets')
category3 = Category(name='Video Gaming')
category4 = Category(name='TV & Home Appliances')
category5 = Category(name='Audio')
category6 = Category(name='Photography')
category7 = Category(name='Womens Fashion')
category8 = Category(name='Mens Fashion')
category9 = Category(name='Bags & Wallets')
category10 = Category(name='Apparel')
category11 = Category(name='Accessories')
category12 = Category(name='Watches')
category13 = Category(name='Sneakers & Footwear')
Area1 = Area(name='Hong Kong Island')
Area2 = Area(name='Kowloon')
Area3 = Area(name='New Territories')
Distric1 = Distric(name='Central and Western')
Distric2 = Distric(name='Eastern')
Distric3 = Distric(name='Islands')
Distric4 = Distric(name='Kowloon City ')
Distric5 = Distric(name='Kwai Tsing')
Distric6 = Distric(name='Kwun Tong')
Distric7 = Distric(name='North')
Distric8 = Distric(name='Sai Kung')
Distric9 = Distric(name='Sham Shui Po')
Distric10 = Distric(name='Sha Tin')
Distric11 = Distric(name='Southern')
Distric12 = Distric(name='Tai Po')
Distric13 = Distric(name='Tsuen Wan')
Distric14 = Distric(name='Tuen Mun')
Distric15 = Distric(name='Wan Chai')
Distric16 = Distric(name='Wong Tai Sin')
Distric17 = Distric(name='Yan Tsim Mong')
Distric18 = Distric(name='Yuen Long')
MTR1 = MTR(name='Admiralty')
MTR2 = MTR(name='Causeway Bay')
MTR3 = MTR(name='Central')
MTR4 = MTR(name='Chai Wan')
MTR5 = MTR(name='Tsim Sha Tsui')
MTR6 = MTR(name='Jordan')
MTR7 = MTR(name='Kennedy Town')
MTR8 = MTR(name='Kowloon Tong')
MTR9 = MTR(name='Kwun Tong')
MTR10 = MTR(name='Lai King')
MTR11 = MTR(name='Lam Tin')
MTR12 = MTR(name='Mong Kok')
MTR13 = MTR(name='Prince Edward')
Condition1 = Condition(name='Brand New')
Condition2 = Condition(name='Like New')
Condition3 = Condition(name='Lightly used')
Condition4 = Condition(name='Well used')
Condition5 = Condition(name='Heavily used')
Meetup1= Meetup(name='Meet-up')
Meetup2= Meetup(name='Mailing & Delivery')
image = Image(name='logo.png')
addproduct1 = Product(productname="good logo",price=133,condition_id=1,meetup_id=2,description="good logo design",image_id=1,category_id=1,brand_id=1,area_id=2,distric_id=3,mtr_id=4,user_id=1)
addproduct2 = Product(productname="carousell",price=1334,condition_id=2,meetup_id=1,description="carousell logo design",image_id=1,category_id=2,brand_id=2,area_id=1,distric_id=4,mtr_id=7,user_id=2)
db.session.add(image)
db.session.add(addproduct1)
db.session.add(addproduct2)
db.session.add(p1)
db.session.add(p2)
db.session.add(brand)
db.session.add(brand1)
db.session.add(category1)
db.session.add(category2)
db.session.add(category3)
db.session.add(category4)
db.session.add(category5)
db.session.add(category6)
db.session.add(category7)
db.session.add(category8)
db.session.add(category9)
db.session.add(category10)
db.session.add(category11)
db.session.add(category12)
db.session.add(category13)
db.session.add(Area1)
db.session.add(Area2)
db.session.add(Area3)
db.session.add(Distric1)
db.session.add(Distric2)
db.session.add(Distric3)
db.session.add(Distric4)
db.session.add(Distric5)
db.session.add(Distric6)
db.session.add(Distric7)
db.session.add(Distric8)
db.session.add(Distric9)
db.session.add(Distric10)
db.session.add(Distric11)
db.session.add(Distric12)
db.session.add(Distric13)
db.session.add(Distric14)
db.session.add(Distric15)
db.session.add(Distric16)
db.session.add(Distric17)
db.session.add(Distric18)
db.session.add(MTR1)
db.session.add(MTR2)
db.session.add(MTR3)
db.session.add(MTR4)
db.session.add(MTR5)
db.session.add(MTR6)
db.session.add(MTR7)
db.session.add(MTR8)
db.session.add(MTR9)
db.session.add(MTR10)
db.session.add(MTR11)
db.session.add(MTR12)
db.session.add(MTR13)
db.session.add(Condition1)
db.session.add(Condition2)
db.session.add(Condition3)
db.session.add(Condition4)
db.session.add(Condition5)
db.session.add(Meetup1)
db.session.add(Meetup2)
#db.session.add(addproduct)
db.session.commit()
